repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.81.0
  hooks:
  - id: terraform_fmt
  - id: terraform_tflint
    args:
    - --args=--config=.tflint.hcl
    - --args=--module
